<?php $parentItem = $this->getItem() ?>
<?php $items = array_merge([$parentItem->getOrderItem()], $parentItem->getOrderItem()->getChildrenItems()) ?>
<?php $poItems = $this->getChilds($parentItem) ?>
<?php $_count = count ($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($poItems as $_poItem): $_item=$_poItem->getOrderItem(); ?>

	<?php if($this->getItemOptions() || $parentItem->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php if ($_item->getParentItem()): ?>
    <?php $attributes = $this->getSelectionAttributes($_item) ?>
    <?php if ($_prevOptionId != $attributes['option_id']): ?>
    <tr>
        <td><div class="option-label"><?php echo $attributes['option_label'] ?></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <?php $_prevOptionId = $attributes['option_id'] ?>
    <?php endif; ?>
<?php endif; ?>
<tr<?php echo (++$_index==$_count && !$_showlastRow)?' class="border"':'' ?> id="order-item-row-<?php echo $_item->getId() ?>">
    <?php if (!$_item->getParentItem()): ?>
    <td><h4 class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></h4></td>
    <?php else: ?>
    <td><div class="option-value"><?php echo $this->getValueHtml($_item) ?></div></td>
    <?php endif; ?>
    <td><?php echo $this->escapeHtml($_item->getSku()) ?></td>
    <td class="a-center">
        <?php if (($this->isShipmentSeparately() && $_item->getParentItem()) || (!$this->isShipmentSeparately() && !$_item->getParentItem())): ?>
            <?php if (isset($poItems[$_item->getId()])): ?>
                <?php echo $poItems[$_item->getId()]->getQty()*1 ?>
            <?php elseif ($_item->getIsVirtual()): ?>
                <?php echo __('N/A') ?>
            <?php else: ?>
                0
            <?php endif; ?>
        <?php else: ?>
        &nbsp;
        <?php endif; ?>
    </td>
</tr>
<?php endforeach; ?>

<?php if ($_showlastRow): ?>
<tr class="border">
    <td>
        <?php if($_options = $this->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
            <?php if (!$this->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
                    <?php echo $_formatedOptionValue['value'] ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                    <div class="truncated_full_value">
                        <dl class="item-options">
                            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                            <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                        </dl>
                    </div>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd><?php echo $this->escapeHtml( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) ) ?></dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php echo $this->escapeHtml($_item->getDescription()) ?>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
<?php endif; ?>
