<div class="wrapper-search" style="background: url( <?php echo $this->getImage(); ?>) #8274a9;background-position: right;background-repeat: no-repeat;">
    <div class="container">
        <div id="search-by-zip">
            <div class="left">
                <div class="cms-block">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage_postalcode_search_text')->toHtml();?>
                </div>
                <div class="wrapper-form">
                    <form action="/" method="post" id="search-by-zip-form">
                        <div class="form-control">
                            <input type="text" name="zip" placeholder="<?php echo __('Entre un code postal'); ?>">
                            <span data-icon="n" class="icon"></span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="arrow"></div>
</div>