<?php
/**
 * @var \Infortis\Base\Block\Catalog\Product\View $block
 */
?>
<?php
    $product = $block->getProduct();
    $abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct');

    $theme = $block->getHelperTheme();
    $helperProductView = $block->getHelperProductView();
    $helperLabels = $this->helper('Infortis\Base\Helper\Labels');
    $helperAddToLinks = $this->helper('Infortis\Base\Helper\AddToLinks');

    //Get grid classes for product page sections
    $grid = $helperProductView->getGridClasses();

    //Get positions of blocks
    $position = $helperProductView->getPositions();

    //Brand info
    $brandHtml = $block->getChildHtml('brand-info');
    if (!empty($brandHtml)) {
        if (isset($p[$position['brand']])) {
            $p[$position['brand']] = $p[$position['brand']] . $brandHtml;
        } else {
            $p[$position['brand']] = $brandHtml;
        }
    }

    //Product collateral data
    $collateralHtml = $block->getChildHtml('product.info.details');
    if (!empty($collateralHtml)) {
        if (isset($p[$position['collateral']])) {
            $p[$position['collateral']] = $p[$position['collateral']] . $collateralHtml;
        } else {
            $p[$position['collateral']] = $collateralHtml;
        }
    }

    //Related products
    $relatedProductsHtml = $block->getChildHtml('catalog.product.related');
    if (!empty($relatedProductsHtml)) {
        if (isset($p[$position['related']])) {
            $p[$position['related']] = $p[$position['related']] . $relatedProductsHtml;
        } else {
            $p[$position['related']] = $relatedProductsHtml;
        }
    }

    //Up-sell products
    $upsellProductsHtml = $block->getChildHtml('product.info.upsell');
    if (!empty($upsellProductsHtml)) {
        if (isset($p[$position['upsell']])) {
            $p[$position['upsell']] = $p[$position['upsell']] . $upsellProductsHtml;
        } else {
            $p[$position['upsell']] = $upsellProductsHtml;
        }
    }

    $disableDeliveryToday = 0; // only 1 or 0;
?>
<div class="product-view product-columns-wrapper">

    <div class="product-img-column <?php echo $grid['imgCol']; ?> no-left-gutter product">

        <?php echo $block->getChildHtml('product.info.media'); ?>
        <?php echo $helperLabels->getLabels($block->getProduct()); ?>
        <?php if (isset($p['imgCol_1'])) echo $p['imgCol_1']; ?>

        <?php //Container at the bottom ?>
        <?php echo $block->getChildHtml('container_product_image_1'); ?>

        <div class="non-collapsing-column-placeholder"></div>

        <p class="description">
            <strong><?php echo __('Product description');?></strong>
            <br>
            <?php echo $product->getDescription();?>
        </p>


    </div>

    <?php //TODO: remove old classes such as "product-shop" (if possible. check it first, test old styles) ?>
    <div class="product-primary-column product-shop <?php echo $grid['primCol']; ?> product-info-main">
        <?php echo $block->getChildHtml('page.main.title'); ?>
<!--        --><?php //echo $block->getChildHtml('product.info.review'); ?>

        <?php //Container at the top ?>
<!--        --><?php //echo $block->getChildHtml('container_product_primary_1'); ?>
        <?php echo $abstractProductBlock->getProductPrice($product); ?>
        <div class="extend-info">
            <p><?php echo __('Choose a delivery date'); ?></p>
            <div class="delivery-select">
                <?php for ($i = 0; $i < 3; $i++): ?>
                    <?php
                        $date = new DateTime();
                        $date->modify('+'.$i.' day');
                    ?>
                    <div class="delivery-block">
                        <p>
                            <?php if ($i == 0): ?>
                                <?php echo __('Today'); ?>
                            <?php else: ?>
                                <?php echo $date->format('D'); ?>
                            <?php endif; ?>
                        </p>
                        <p>
                            <?php echo $date->format('j'); ?>
                            <?php echo $date->format('M'); ?>
                        </p>
                    </div>
                <?php endfor; ?>


                <div class="delivery-block" id="select-custom-date">
                    <p>
                        <?php echo __('Full calendar'); ?>
                    </p>
                    <p>
                        &nbsp;
                    </p>
                    <input type="text" name="custom_date" id="custom-date">
                </div>
            </div>

            <button id="order-now" type="submit" class="btn"><?php echo __('Order now'); ?></button>
        </div>
<!--        --><?php //if (isset($p['primCol_1'])) echo $p['primCol_1']; ?>
<!--        --><?php //echo $block->getChildHtml('product.info.main'); ?>
<!--        --><?php //if (isset($p['primCol_2'])) echo $p['primCol_2']; ?>

        <?php //Container at the bottom ?>
        <?php echo $block->getChildHtml('container_product_primary_2'); ?>

    </div>

    <div class="product-primary-column product-shop grid12-6 seller-wrapper">
        <div class="wrapper-seller-avatar">
            <img src="http://www.rajahmundryeshop.com/images/Homepg/GESF027.jpg">
        </div>
        <div class="seller-info">
            <p class="seller-name">Seller name</p>
            <p class="city-name">City name</p>
            <p class="">
                <div class="ratings">
                    <div class="rating-box">
                        <div class="rating" style="width:20%"></div>
                    </div>
                </div>
            </p>
        </div>
    </div>
    
    <?php if (isset($grid['secCol'])): ?>

        <div class="product-secondary-column custom-sidebar-right <?php echo $grid['secCol']; ?> no-right-gutter">
            <div class="inner">

                <?php //Container at the top ?>
                <?php echo $block->getChildHtml('container_product_secondary_1'); ?>

                <?php if (isset($p['secCol_1'])) echo $p['secCol_1']; ?>
                <?php echo $block->getChildHtml('block_product_secondary_bottom'); ?>
                <?php if (isset($p['secCol_2'])) echo $p['secCol_2']; ?>

                <?php //Container at the bottom ?>
                <?php echo $block->getChildHtml('container_product_secondary_2'); ?>

                <?php //if (isset($p['secCol_3'])) echo $p['secCol_3']; ?>

                <?php //TODO: ?>
                <?php if ($tmpHtml = $block->getChildHtml('product_secondary_top_placeholder')): ?>
                    <div class="feature-wrapper bottom-border"><?php echo $tmpHtml; ?></div>
                <?php endif; ?>

            </div>
        </div>

    <?php endif; ?>

    <div class="product-lower-primary-column <?php echo $grid['lowerPrimCol']; ?>">

        <?php echo $block->getChildHtml('bundle.options.container'); ?>
        <?php echo $block->getChildHtml('moved.downloadable.product-info'); ?>

        <?php //Container at the top. Important: required AFTER the bundle and downloadable blocks. ?>
        <?php echo $block->getChildHtml('container_product_lower_primary_1'); ?>

        <?php if (isset($p['lowerPrimCol_1'])) echo $p['lowerPrimCol_1']; ?>

        <?php //Container at the bottom ?>
        <?php echo $block->getChildHtml('container_product_lower_primary_2'); ?>

    </div>

    <?php if (isset($grid['lowerSecCol'])): ?>

        <div class="product-lower-secondary-column custom-sidebar-right <?php echo $grid['lowerSecCol']; ?>">
            <div class="inner">

                <?php //Container at the top ?>
                <?php echo $block->getChildHtml('container_product_lower_secondary_1'); ?>

                <?php if (isset($p['lowerSecCol_1'])) echo $p['lowerSecCol_1']; ?>

                <?php //Container at the bottom ?>
                <?php echo $block->getChildHtml('container_product_lower_secondary_2'); ?>

            </div>
        </div>

    <?php endif; ?>

</div>

<script type="text/javascript">
    //<![CDATA[
    requirejs(['jquery'], function(jQuery) {
        jQuery(function($) {
            var currentDate = new Date();
            $('.delivery-block').click(function(){
                $('.delivery-block').removeClass('active');
                $(this).addClass('active');
            });


            var deliveryCalendar = {
                currentDate: new Date(),
                disableDeliveryToday: 0,
                init: function(selector,disableDeliveryToday){
                    var self = this;
                    this.disableDeliveryToday = disableDeliveryToday;
                    this.bindEvent();
                    $('#custom-date').datepicker({
                        minDate: new Date(currentDate.getFullYear(), currentDate.getMonth() ,currentDate.getDate() + self.disableDeliveryToday),
                        onSelect: self.selectDate
                    })
                },
                selectDate: function(selectedDate, event){
                    deliveryCalendar.checkExistSelection(new Date(selectedDate),2,function(existSelection){ //Here i was use main deliveryCalendar object, because i don't know how use link for this object here (just object)
                        if (existSelection !== false){
                            //Selected date exists, and we automatically choose it
                            $('.delivery-select>div:eq('+existSelection+')').click()
                        }
                        else{

                        }
                    });
                },
                bindEvent: function(){
                    var self = this;
                    $('#select-custom-date').click(function(){
                        $('#custom-date').datepicker("show");
                    })
                },
                checkExistSelection: function(selectedDate, day, callback){
                    var existSelection = false;
                    for (day;day>=0;day--){
                        var exactDate = new Date(this.currentDate.getFullYear(), this.currentDate.getMonth(), this.currentDate.getDate() + day);
                        if (exactDate.getFullYear() == selectedDate.getFullYear() && exactDate.getMonth() == selectedDate.getMonth() && exactDate.getDate() == selectedDate.getDate()) {
                            existSelection = day;
                            break;
                        }
                    }
                    callback(existSelection);
                }
            };
            deliveryCalendar.init('#custom-date',<?php echo (int) $disableDeliveryToday; ?>);
        });

    });
    //]]>
</script>