<?php
//TO DO: need gen correct links through getUrl
?>
<div id="header-account" class="account-links top-links links-wrapper-separators-left skip-content skip-content--style">
    <ul class="header links">
        <li>
            <a href="#">
                <?php echo __('Registration / Login'); ?>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="/customer/account/login/">
                        <?php echo __('I am a customer'); ?>
                    </a>
                </li>
                <li>
                    <a href="/udropship/">
                        <?php echo __('I am a flower seller'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/aide">
                <?php echo __('Help'); ?>
            </a>
        </li>
    </ul>
</div>